name: flutter_alpha_player
description: The plugin is a flutter version of the flutter implementation bytedance from AlphaPlayer
version: 0.0.2
homepage: https://github.com/TralyFang/alpha_player_plugin
repository: https://github.com/TralyFang/alpha_player_plugin.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.alpha_player_plugin
        pluginClass: AlphaPlayerPlugin
      ios:
        pluginClass: AlphaPlayerPlugin